version: 2
updates:
  # Enable version updates for npm
  - package-ecosystem: "npm"
    # Look for package.json and yarn.lock files in the `root` directory
    directory: "/"
    # Check for updates once a week (on Monday)
    schedule:
      interval: "weekly"
      day: "monday"
    # Groups all patch and minor updates together into a single PR
    groups:
      minor-patch-dependencies:
        update-types:
          - "minor"
          - "patch"
    # Add reviewers to pull requests
    reviewers:
      - "DillonOLeary"
    # Specify labels for pull requests
    labels:
      - "dependencies"
    # Limit the number of open PRs Dependabot can have
    open-pull-requests-limit: 10
    # Set security updates to high priority
    allow:
      - dependency-type: "direct"
      - dependency-type: "indirect"
    commit-message:
      prefix: "deps"
      prefix-development: "dev-deps"
      include: "scope"

  # Enable version updates for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    reviewers:
      - "DillonOLeary"
    labels:
      - "dependencies"
      - "github-actions"
    commit-message:
      prefix: "ci"
      include: "scope"