name: PR Format Check

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  format:
    name: Format Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
      
      - name: Enable Corepack
        run: corepack enable
      
      - name: Setup Yarn
        run: corepack prepare yarn@4.1.0 --activate

      - name: Install dependencies
        run: yarn install --immutable --mode=skip-build

      - name: Check formatting
        run: yarn format:check